spring.application.name=ingestion-service

# Kafka Producer Properties
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
# This is the "Magic Line" that handles the JSON conversion
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Optional: Add the Type Info so the consumer knows it's a MainframeRecord
spring.kafka.producer.properties.spring.json.add.type.headers=true
