spring.application.name=ingestion-service

spring.kafka.admin.properties.retry.backoff.ms=5000
spring.kafka.admin.properties.reconnect.backoff.ms=5000
# Kafka Producer Properties
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
# This is the "Magic Line" that handles the JSON conversion
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Optional: Add the Type Info so the consumer knows it's a MainframeRecord
spring.kafka.producer.properties.spring.json.add.type.headers=true

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}


